name: Build and Test Workflow

on:
  push:
    branches: [main, feature/github-actions]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install Dependencies
        run: go get .

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -short
